url: "https://blake.app"
baseurl: ""
title: "blake.app"
permalink: /blog/:title/
author: Blake Erickson
description: Blake Erickson's personal blog

plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge

feed:
  path: /blog/feed.xml